"""add reset code fields

Revision ID: 1d6a5cbfaab2
Revises: b67a3d2d6de6
Create Date: 2026-05-29 00:43:42.683153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d6a5cbfaab2'
down_revision = 'b67a3d2d6de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('reset_code_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_code_expiry')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
